name = "My 1.21.1 Pack"
author = "you"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f7cd62e5d86a0c4a3ca7ac722baeab0e67401602c48e161f4cd53ab9238cdb3f"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
