name = "My 1.21.1 Pack"
author = "you"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1f190cda35ba43e02cdaba61f5b218acea6f1cb4a31d5cd2cf5f6020dcb6558e"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
