name = "My 1.21.1 Pack"
author = "you"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "276e03d11586b133b2425f2dbac15c394ba6db0ffc48a1eede42374bb1ee144a"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
