name = "My 1.21.1 Pack"
author = "you"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2e666d13c75f6ed956a82b9616d750615082bdcb907af366f98a0bf5700a02e8"

[versions]
fabric = "0.18.0"
minecraft = "1.21.1"
