name = "My 1.21.1 Pack"
author = "you"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "968156f6e5edf6bc789961fce60d59c87cb2396635b18418150b161d8ce75e56"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
